### PR TITLE
dynamic battery icon templates

### PR DESCRIPTION
**Pull request by ntalekt**
Thought you would like this tweak.

### CODE REVIEW

**Comment by geekofweek** [comment]
Interesting idea, not something I was looking for (I rarely let my batteries go that low), but since you did all the work already it's worth it.  In theory should be able to add different icons for each step down.  Nice work and Thanks!

**Comment by philhawthorne** [comment]
Nice one @ntalekt 

Going to use this as well!

**Comment by ntalekt** [comment]
It takes the battery sensor and rounds it, then applies the correct icon for each 10% step. I stole it from @DubhAd who stole it from @skalavala.

**Comment by geekofweek** [comment]
After removing the hard coded battery icons I forgot about, this is working out nicely.  Appreciated tweak, nice work.

**Pull request merged**
